# Generated by Django 2.2.4 on 2019-08-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190822_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='views',
            new_name='nviews',
        ),
    ]
